import Head from "next/head";
import useDarkMode from "../../helpers/useDarkMode";
import Navbar from "../../components/Navbar";
import ProjectDetail from "../../components/ProjectDetail";
import Link from "next/link";
import { HiOutlineChevronLeft, HiOutlineChevronRight } from "react-icons/hi";

function Teatalk() {
  const [colorTheme, setTheme] = useDarkMode();
  return (
    <div className="w-screen min-h-screen dark:bg-gray-900 bg-indigo-200">
      <Head>
        <title>Shelda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="sm:w-[475px] lg:w-[800px] mx-auto">
        <ProjectDetail />
        <div className="mx-6 border-t-2 my-7 lg:my-14 dark:border-indigo-200 border-gray-900" />

        <Link href={"/project/healthymed"}>
          <div className="lg:text-xl dark:text-indigo-200 text-gray-900 flex items-center justify-end mx-6 pb-6">
            Next project: Healthymed
            <HiOutlineChevronRight className="text-lg ml-3" />
          </div>
        </Link>
      </div>
    </div>
  );
}

export default Teatalk;
